name: softpro-test-case
services:
  node:
    image: node:20
    container_name: node
    env_file: ../.env
    working_dir: /app
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - '5010:5010'
    command: sh -c "npm install  && npm run build && npm run dev"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:16.3
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d/
    entrypoint: >
      sh -c "chmod +x /docker-entrypoint-initdb.d/init-db.sh && exec docker-entrypoint.sh postgres"
    ports:
      - "5432:5432"
    env_file: ../.env
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    env_file: ../.env
    ports:
      - "6379:6379"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge